/*
* a:byc
* time:2024/3/28
* des:
*/

export default class UColors {
  static readonly theme_color = $r('app.color.theme_color')
  static readonly common_bg = $r('app.color.common_bg')
  static readonly text_color3 = $r('app.color.text_color3')
  static readonly text_color6 = $r('app.color.text_color6')
  static readonly text_color9 = $r('app.color.text_color9')
  static readonly cf4f5f6 = $r('app.color.cf4f5f6')
  static readonly cf5f5f5 = $r('app.color.cf5f5f5')
  static readonly white = $r('app.color.white')
}