/*
* a:byc
* time:2024/3/28
* des:
*/

export default class USizes {
  static readonly match_parent = '100%';
  static readonly vp200 = '200vp';
  static readonly vp100 = '100vp';
  static readonly vp80 = '80vp';
  static readonly vp60 = '60vp';
  static readonly vp50 = '50vp';
  static readonly vp40 = '40vp';
  static readonly vp30 = '30vp';
  static readonly vp20 = '20vp';
  static readonly vp16 = '16vp';
  static readonly vp14 = '14vp';
  static readonly vp12 = '12vp';
  static readonly vp10 = '10vp';
  static readonly vp8 = '8vp';
  static readonly vp6 = '6vp';
  static readonly vp5 = '5vp';
  static readonly vp4 = '4vp';
  static readonly vp2 = '2vp';
  static readonly vp1 = '1vp';
  static readonly fp8 = '8fp';
  static readonly fp12 = '12fp';
  static readonly fp14 = '14fp';
  static readonly fp16 = '16fp';
  static readonly fp18 = '18fp';
  static readonly fp20 = '20fp';
  static readonly fp40 = '40fp';
  static readonly fp60 = '60fp';
}